# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.simlife.io/profiles/
# More information on configuration properties: https://www.simlife.io/common-application-properties/
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

logging:
    level:
        ROOT: DEBUG
        io.github.simlife: DEBUG
        io.github.crawlerbot: DEBUG

eureka:
    instance:
        prefer-ip-address: true
    client:
        service-url:
            defaultZone: http://admin:${simlife.registry.password}@140.203.154.235:8761/eureka/

spring:
    profiles:
        active: dev
        include: swagger
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: false # we use Webpack dev server + BrowserSync for livereload
    jackson:
        serialization.indent_output: true


    cloud.stream.kafka.streams.binder.configuration.commit.interval.ms: 1000
    cloud.stream.kafka.bindings.output.producer.configuration.max.block.ms: 5000
    cloud.stream.kafka.binder.brokers: 140.203.155.14
    cloud.stream.kafka.binder.zk-nodes: 140.203.155.14
    cloud.stream.bindings.singleOutput.contentType: application/json
    cloud.stream.bindings.messageChannel.destination: crawl
    cloud.stream.bindings.messageChannel.content-type: application/json
    cloud.stream.bindings.subscribableChannel.destination: crawl


    data:
        mongodb:
            uri: mongodb://140.203.155.14:27018
            database: CrawlerWorker
        elasticsearch:
            cluster-name: elasticsearch
            cluster-nodes: 140.203.155.14:9300

    mail:
        host: localhost
        port: 25
        username:
        password:
    messages:
        cache-duration: PT1S # 1 second, see the ISO 8601 standard
    thymeleaf:
        cache: false
    zipkin: # Use the "zipkin" Maven profile to have the Spring Cloud Zipkin dependencies
        base-url: http://localhost:9411
        enabled: false
        locator:
            discovery:
                enabled: true

# ===================================================================
# To enable SSL, generate a certificate using:
# keytool -genkey -alias crawlerworker -storetype PKCS12 -keyalg RSA -keysize 2048 -keystore keystore.p12 -validity 3650
#
# You can also use Let's Encrypt:
# https://maximilian-boehm.com/hp2121/Create-a-Java-Keystore-JKS-from-Let-s-Encrypt-Certificates.htm
#
# Then, modify the server.ssl properties so your "server" configuration looks like:
#
# server:
#    port: 8443
#    ssl:
#        key-store: keystore.p12
#        key-store-password: <your-password>
#        key-store-type: PKCS12
#        key-alias: crawlerworker
# ===================================================================
server:
    port: 8081

# ===================================================================
# Simlife specific properties
#
# Full reference is available at: https://www.simlife.io/common-application-properties/
# ===================================================================

simlife:
    http:
        version: V_1_1 # To use HTTP/2 you will need SSL support (see above the "server.ssl" configuration)
    # CORS is disabled by default on microservices, as you should access them through a gateway.
    # If you want to enable it, please uncomment the configuration below.
    # cors:
        # allowed-origins: "*"
        # allowed-methods: "*"
        # allowed-headers: "*"
        # exposed-headers: "Authorization,Link,X-Total-Count"
        # allow-credentials: true
        # max-age: 1800
    security:
        authentication:
            jwt:
                secret: my-secret-token-to-change-in-production
                # Token is valid 24 hours
                token-validity-in-seconds: 86400
                token-validity-in-seconds-for-remember-me: 2592000
    mail: # specific Simlife mail property, for standard properties see MailProperties
        from: worker@localhost
        base-url: http://127.0.0.1:8081
    metrics: # DropWizard Metrics configuration, used by MetricsConfiguration
        jmx:
            enabled: true
        logs: # Reports Dropwizard metrics in the logs
            enabled: false
            report-frequency: 60 # in seconds
    logging:
        logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
            enabled: false
            host: localhost
            port: 5000
            queue-size: 512

# ===================================================================
# Application specific properties
# Add your own application properties here, see the ApplicationProperties class
# to have type-safe configuration, like in the SimlifeProperties above
#
# More documentation is available at:
# https://www.simlife.io/common-application-properties/
# ===================================================================

# application:
