version: '2'
services:
    crawlerworker-app:
        image: crawlerworker
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${simlife.registry.password}@simlife-registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${simlife.registry.password}@simlife-registry:8761/config
            - SPRING_DATA_MONGODB_URI=mongodb://crawlerworker-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=CrawlerWorker
            - SIMLIFE_SLEEP=30 # gives time for the Simlife Registry to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=crawlerworker-elasticsearch:9300
            - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka
            - SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES=zookeeper
    crawlerworker-mongodb:
        extends:
            file: mongodb.yml
            service: crawlerworker-mongodb
    crawlerworker-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: crawlerworker-elasticsearch
    kafka:
        extends:
            file: kafka.yml
            service: kafka
        environment:
            - KAFKA_ADVERTISED_HOST_NAME=kafka
    zookeeper:
        extends:
            file: kafka.yml
            service: zookeeper
    simlife-registry:
        extends:
            file: simlife-registry.yml
            service: simlife-registry
        environment:
            - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:./central-config/docker-config/
